In [1]:
import pandas as pd
from datetime import date, time
from datetime import datetime, timedelta

pd.set_option('display.max_columns', None) #parametro para apresentar colunas ocultas do dataframe

In [2]:
df1 = pd.read_csv('dfs/1_azul.csv')
df2 = pd.read_csv('dfs/2_amarela.csv')
df3 = pd.read_csv('dfs/3_rosa.csv')
df4 = pd.read_csv('dfs/4_verde.csv')
df5 = pd.read_csv('dfs/5_vermelha.csv')
df6 = pd.read_csv('dfs/6_laranja.csv')

In [3]:
df1.head(5)

,CENTRAL DE CAMIONAGEM,LARGO DE CAMÕES,AV. DR. ALFR. SOUSA (MULTIUSOS),AV. DR. ALFREDO SOUSA (CTT),MEIA LARANJA,ARNEIRÓS (CEMITÉRIO STA. CRUZ),ARNEIRÓS (ESCOLA DE HOTELARIA),ARNEIRÓS (RESTAURANTE TONEL),ESCOLA DE ARNEIRÓS,ARNEIRÓS,ARNEIRÓS (LAR),CARREIRA DE TIRO,LAMELAS,PENUDE,TIMPEIRA,QTA. BORBULHÃO,SRA. DA GUIA,MEDELO,CAPELA MÁRTIR S. SEBASTIÃO,ROT. DR. FERNANDO AMARAL,ESCOLA EB 2/3,CENTRO DE SAÚDE,FAFEL/AV. 5 DE OUTUBRO (CRUZ.),MERCADO MUNICIPAL,AV. DR. ALFR. SOUSA (MULTIUSOS).1,AV. DR. ALFREDO SOUSA (CTT).1,LARGO DE CAMÕES.1,CENTRAL DE CAMIONAGEM.1,sabado
0,8:00,8:01,8:02,8:03,8:04,8:06,8:08,8:09,8:10,8:11,8:12,8:13,8:14,8:15,8:16,8:17,8:18,8:19,8:20,8:21,8:22,8:23,8:24,8:25,8:26,8:27,8:28,8:29,0
1,9:00,9:01,9:02,9:03,9:04,9:06,9:08,9:09,9:10,9:11,9:12,9:13,9:14,9:15,9:16,9:17,9:18,9:19,9:20,9:21,9:22,9:23,9:24,9:25,9:26,9:27,9:28,9:29,0
2,10:00,10:01,10:02,10:03,10:04,10:06,10:08,10:09,10:10,10:11,10:12,10:13,10:14,10:15,10:16,10:17,10:18,10:19,10:20,10:21,10:22,10:23,10:24,10:25,10:26,10:27,10:28,10:29,0
3,12:00,12:01,12:02,12:03,12:04,12:06,12:08,12:09,12:10,12:11,12:12,12:13,12:14,12:15,12:16,12:17,12:18,12:19,12:20,12:21,12:22,12:23,12:24,12:25,12:26,12:27,12:28,12:29,0
4,13:00,13:01,13:02,13:03,13:04,13:06,13:08,13:09,13:10,13:11,13:12,13:13,13:14,13:15,13:16,13:17,13:18,13:19,13:20,13:21,13:22,13:23,13:24,13:25,13:26,13:27,13:28,13:29,0

Converter as horas dos Dataframes que estão em formato String para Time

In [4]:
# alterando tipo de dados para data no dataframe 1
for column in df1.columns[:-1]:
    # Convert the Time column to datatime format
    df1[column] = pd.to_datetime(df1[column], format='%H:%M').dt.time
    '''.dt é um acessador (accessor) no pandas que permite acessar
    várias propriedades de um objeto datetime. O .time é uma dessas
    propriedades, que retorna o componente de tempo do objeto datetime.'''
    
# alterando tipo de dados para data no dataframe 2
for column in df2.columns[:-1]:
    # Convert the Time column to datatime format
    df2[column] = pd.to_datetime(df2[column], format='%H:%M').dt.time

# alterando tipo de dados para data no dataframe 3
for column in df3.columns[:-1]:
    # Convert the Time column to datatime format
    df3[column] = pd.to_datetime(df3[column], format='%H:%M').dt.time

# alterando tipo de dados para data no dataframe 4
for column in df4.columns[:-1]:
    # Convert the Time column to datatime format
    df4[column] = pd.to_datetime(df4[column], format='%H:%M').dt.time

# alterando tipo de dados para data no dataframe 5
for column in df5.columns[:-2]:
    # Convert the Time column to datatime format
    df5[column] = pd.to_datetime(df5[column], format='%H:%M').dt.time

# alterando tipo de dados para data no dataframe 6
for column in df6.columns[:-1]:
    # Convert the Time column to datatime format
    df6[column] = pd.to_datetime(df6[column], format='%H:%M').dt.time

In [5]:
df1.head(50)

,CENTRAL DE CAMIONAGEM,LARGO DE CAMÕES,AV. DR. ALFR. SOUSA (MULTIUSOS),AV. DR. ALFREDO SOUSA (CTT),MEIA LARANJA,ARNEIRÓS (CEMITÉRIO STA. CRUZ),ARNEIRÓS (ESCOLA DE HOTELARIA),ARNEIRÓS (RESTAURANTE TONEL),ESCOLA DE ARNEIRÓS,ARNEIRÓS,ARNEIRÓS (LAR),CARREIRA DE TIRO,LAMELAS,PENUDE,TIMPEIRA,QTA. BORBULHÃO,SRA. DA GUIA,MEDELO,CAPELA MÁRTIR S. SEBASTIÃO,ROT. DR. FERNANDO AMARAL,ESCOLA EB 2/3,CENTRO DE SAÚDE,FAFEL/AV. 5 DE OUTUBRO (CRUZ.),MERCADO MUNICIPAL,AV. DR. ALFR. SOUSA (MULTIUSOS).1,AV. DR. ALFREDO SOUSA (CTT).1,LARGO DE CAMÕES.1,CENTRAL DE CAMIONAGEM.1,sabado
0,08:00:00,08:01:00,08:02:00,08:03:00,08:04:00,08:06:00,08:08:00,08:09:00,08:10:00,08:11:00,08:12:00,08:13:00,08:14:00,08:15:00,08:16:00,08:17:00,08:18:00,08:19:00,08:20:00,08:21:00,08:22:00,08:23:00,08:24:00,08:25:00,08:26:00,08:27:00,08:28:00,08:29:00,0
1,09:00:00,09:01:00,09:02:00,09:03:00,09:04:00,09:06:00,09:08:00,09:09:00,09:10:00,09:11:00,09:12:00,09:13:00,09:14:00,09:15:00,09:16:00,09:17:00,09:18:00,09:19:00,09:20:00,09:21:00,09:22:00,09:23:00,09:24:00,09:25:00,09:26:00,09:27:00,09:28:00,09:29:00,0
2,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:06:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,0
3,12:00:00,12:01:00,12:02:00,12:03:00,12:04:00,12:06:00,12:08:00,12:09:00,12:10:00,12:11:00,12:12:00,12:13:00,12:14:00,12:15:00,12:16:00,12:17:00,12:18:00,12:19:00,12:20:00,12:21:00,12:22:00,12:23:00,12:24:00,12:25:00,12:26:00,12:27:00,12:28:00,12:29:00,0
4,13:00:00,13:01:00,13:02:00,13:03:00,13:04:00,13:06:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,0
5,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:06:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,0
6,16:00:00,16:01:00,16:02:00,16:03:00,16:04:00,16:06:00,16:08:00,16:09:00,16:10:00,16:11:00,16:12:00,16:13:00,16:14:00,16:15:00,16:16:00,16:17:00,16:18:00,16:19:00,16:20:00,16:21:00,16:22:00,16:23:00,16:24:00,16:25:00,16:26:00,16:27:00,16:28:00,16:29:00,0
7,17:00:00,17:01:00,17:02:00,17:03:00,17:04:00,17:06:00,17:08:00,17:09:00,17:10:00,17:11:00,17:12:00,17:13:00,17:14:00,17:15:00,17:16:00,17:17:00,17:18:00,17:19:00,17:20:00,17:21:00,17:22:00,17:23:00,17:24:00,17:25:00,17:26:00,17:27:00,17:28:00,17:29:00,0
8,18:00:00,18:01:00,18:02:00,18:03:00,18:04:00,18:06:00,18:08:00,18:09:00,18:10:00,18:11:00,18:12:00,18:13:00,18:14:00,18:15:00,18:16:00,18:17:00,18:18:00,18:19:00,18:20:00,18:21:00,18:22:00,18:23:00,18:24:00,18:25:00,18:26:00,18:27:00,18:28:00,18:29:00,0
9,19:00:00,19:01:00,19:02:00,19:03:00,19:04:00,19:06:00,19:08:00,19:09:00,19:10:00,19:11:00,19:12:00,19:13:00,19:14:00,19:15:00,19:16:00,19:17:00,19:18:00,19:19:00,19:20:00,19:21:00,19:22:00,19:23:00,19:24:00,19:25:00,19:26:00,19:27:00,19:28:00,19:29:00,0
10,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:06:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,1
11,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:06:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,1
12,15:00:00,15:01:00,15:02:00,15:03:00,15:04:00,15:06:00,15:08:00,15:09:00,15:10:00,15:11:00,15:12:00,15:13:00,15:14:00,15:15:00,15:16:00,15:17:00,15:18:00,15:19:00,15:20:00,15:21:00,15:22:00,15:23:00,15:24:00,15:25:00,15:26:00,15:27:00,15:28:00,15:29:00,1

Forma de calcular a diferença entre datas.

foi adicionado a data atual a hora, pq não é possível, segundo pesquisas, calcular a diferença somente entre horas... 
sendo necessário combinar alguma data, no caso, a data atual (datetime.today()).

Para encontrar a menor diferença de tempo entre uma coluna de horas em um DataFrame pandas e a hora atual, você pode seguir os seguintes passos:

In [23]:
# Obter a hora atual
def HoraAutocarro(nome_paragem,nome_rota):

    agora = datetime.now()
    hora_atual = agora
    #hora_atual = agora + timedelta(days=-1) #DIA ADIANTADO
    #hora_atual = agora + timedelta(hours=6) #HORA ADIANTADA


    #filtragem (retirada) das horas inferiores a hora atual
    df_filtrado = nome_rota[nome_rota[nome_paragem] >= hora_atual.time()]

    #verificar o dia da semana para filtrar a base de dados
    if hora_atual.weekday() == 6: #hj é domingo!
        print("Não existem autocarros para o dia de hoje!)")

    elif hora_atual.weekday() == 5: #hj é sábado!
        df_sabado = df_filtrado.query('sabado  == 1')

        # Calcular a diferença de tempo entre cada valor na coluna de horários da paragem e a hora atual
        df_sabado['diferenca'] = df_sabado[nome_paragem].apply(lambda x: datetime.combine(datetime.today(), x) - datetime.combine(datetime.today(), hora_atual.time()))

        # Encontrar a menor diferença de tempo
        menor_diferenca = df_sabado['diferenca'].min()

        # Encontrar o índice da hora mais próxima
        indice_hora_proxima = df_sabado['diferenca'].idxmin()

        # Obter a hora mais próxima
        hora_proxima = df_sabado.loc[indice_hora_proxima, nome_paragem]

        # Exibir a menor diferença de tempo e a hora mais próxima
        print("Hora atual: ", hora_atual.time())
        print("Tempo de espera:", menor_diferenca)
        print("Próximo autocarro:", hora_proxima)

    elif hora_atual.weekday() < 5: #hj é dia da semana!
        df_semana = df_filtrado.query('sabado  == 0')

        # Calcular a diferença de tempo entre cada valor na coluna de horários da paragem e a hora atual
        df_semana['diferenca'] = df_semana[nome_paragem].apply(lambda x: datetime.combine(datetime.today(), x) - datetime.combine(datetime.today(), hora_atual.time()))

        # Encontrar a menor diferença de tempo
        menor_diferenca = df_semana['diferenca'].min()

        # Encontrar o índice da hora mais próxima
        indice_hora_proxima = df_semana['diferenca'].idxmin()

        # Obter a hora mais próxima
        hora_proxima = df_semana.loc[indice_hora_proxima, nome_paragem]

        # Exibir a menor diferença de tempo e a hora mais próxima
        print("dia da semana: ", hora_atual.weekday())
        print("Hora atual: ", hora_atual.time())
        print("Tempo de espera:", menor_diferenca)
        print("Próximo autocarro:", hora_proxima)

In [24]:
HoraAutocarro('LARGO DE CAMÕES',df1)
print('-----------------------------------------------------')
HoraAutocarro('CENTRAL DE CAMIONAGEM',df2)

dia da semana:  3
Hora atual:  11:23:28.921042
Tempo de espera: 0 days 00:37:31.078958
Próximo autocarro: 12:01:00
-----------------------------------------------------
dia da semana:  3
Hora atual:  11:23:28.929021
Tempo de espera: 0 days 00:36:31.070979
Próximo autocarro: 12:00:00

C:\Users\GEOME188\AppData\Local\Temp\ipykernel_18364\2087561924.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_semana['diferenca'] = df_semana[nome_paragem].apply(lambda x: datetime.combine(datetime.today(), x) - datetime.combine(datetime.today(), hora_atual.time()))
C:\Users\GEOME188\AppData\Local\Temp\ipykernel_18364\2087561924.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_semana['diferenca'] = df_semana[nome_paragem].apply(lambda x: datetime.combine(datetime.today(), x) - datetime.combine(datetime.today(), hora_atual.time()))

Visualizar os dados em um mapa Folium

In [27]:
import folium
import geopandas as gpd
from shapely import Point

paragem = gpd.read_file("./shp/paragem_autocarro_lamego.shp")



m = folium.Map(#width=600, height=600,
           location=[paragem.geometry.y.mean(), paragem.geometry.x.mean()],
           zoom_start=14,
           tiles='OpenStreetMap'
           )

# grupo de layers
shapesparegem = folium.FeatureGroup(name= 'Paragem').add_to(m)

'''folium.GeoJson(
    paragem,
    popup= 'teste',
    zoom_on_click=True, #centraliza a pag no ponto clicado
    style_function=lambda feature: {
        'fillColor': 'green',
        'color': 'darkred',
        'weight': 0.1,
        'icon': 'bus'
    }
).add_to(m)'''


for id in range(paragem.shape[0]):

    location = [paragem['geometry'][id].y, paragem['geometry'][id].x]
    icon = folium.features.CustomIcon("./img/icon_bus.png", icon_size=(20,20)) 
    popup = folium.Popup("<strong>Paragem:</strong><br>" + HoraAutocarro(str(paragem['nome'][id]),df + '<br>', max_width=500)

    marker= folium.Marker(
        location=location,
        popup=popup,
        tooltip='<strong>'+ str(paragem['nome'][id]) + '</strong>',
        icon=icon

    ).add_to(shapesparegem)


folium.LayerControl().add_to(m)

m.save('output.html')

In [14]:
paragem.head(50)

,nome,lat,long,rota_1,rota_2,rota_3,rota_4,rota_5,rota_6,geometry
0,hotel lamego,41.1023498,-7.7984748,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.79847 41.10235)
1,Rua De S. João,41.1004646,-7.8018704,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.80187 41.10046)
2,CASA DAS BROLHAS,41.0956335,-7.8047405,0.0,1.0,1.0,0.0,0.0,1.0,POINT (-7.80474 41.09563)
3,largo dr joao de almeida,41.0945945,-7.8063551,0.0,1.0,1.0,0.0,0.0,0.0,POINT (-7.80636 41.09459)
4,MEIA LARANJA,41.0932949,-7.8111735,1.0,1.0,1.0,0.0,0.0,0.0,POINT (-7.81117 41.09329)
5,continente,41.1006903,-7.8166973,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.81670 41.10069)
6,Pingo Doce,None,None,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.80507 41.09966)
7,CENTRAL DE CAMIONAGEM,None,None,1.0,1.0,1.0,1.0,1.0,1.0,POINT (-7.80583 41.09805)
8,LECRERC,None,None,0.0,1.0,1.0,0.0,0.0,0.0,POINT (-7.79842 41.09006)
9,Urbanização Vista Alegre,41.1024527,-7.795523,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.79552 41.10245)
10,Quinta Ferraz,41.1011196,-7.8030707,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.80307 41.10112)
11,Souto covo,41.1072833,-7.7989331,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.79893 41.10728)
12,CASA DA LAVOURA,41.0943688,-7.8044053,0.0,1.0,1.0,0.0,0.0,1.0,POINT (-7.80441 41.09437)
13,Escola Secund. da Sé,41.0927644,-7.8046458,0.0,1.0,1.0,0.0,0.0,0.0,POINT (-7.80483 41.09272)
14,Av dr Egas Moniz,41.0899886,-7.8042715,0.0,1.0,1.0,0.0,0.0,0.0,POINT (-7.80423 41.08993)
15,ESCOLA RURAL,41.0858487,-7.7986962,0.0,1.0,1.0,0.0,0.0,0.0,POINT (-7.79885 41.08576)
16,Lidl,41.0810654,-7.7986777,0.0,1.0,1.0,0.0,0.0,0.0,POINT (-7.79868 41.08107)
17,PSP,41.1039701,-7.8099038,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.80990 41.10397)
18,Fafel / Av. 5 de outubro (Cruz.),41.0979569,-7.8117978,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.81166 41.09805)
19,Escola EB 2/3,41.0968857,-7.8169981,1.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.81700 41.09689)
20,Nazes,41.1008809,-7.8140608,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.81406 41.10088)
21,Cantina / câmara Lamego,41.1032875,-7.8116305,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.81163 41.10329)
22,Unidade de Saúde Familiar,None,None,0.0,0.0,0.0,1.0,1.0,0.0,POINT (-7.81089 41.10009)
23,Urb. Encosta do Sol,None,None,0.0,0.0,0.0,1.0,0.0,0.0,POINT (-7.81368 41.10256)
24,Calvilhe,None,None,0.0,0.0,1.0,0.0,0.0,0.0,POINT (-7.79903 41.07841)
25,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-7.81642 41.09761)
26,Balsemão (Cruz),None,None,NaN,NaN,3.0,NaN,NaN,NaN,POINT (-7.80223 41.09171)

In [15]:
df2.head()

,CENTRAL DE CAMIONAGEM,LARGO DE CAMÕES,AV. DR. ALFR. SOUSA (MULTIUSOS),AV. DR. ALFREDO SOUSA (CTT),MEIA LARANJA,LARGO DR. JOÃO DE ALMEIDA,ESCOLA SECUNDÁRIA DA SÉ,AV. DR. EGAS MONIZ (TAMBOREIRA),LECRERC,ESCOLA RURAL,HOSPITAL,LIDL,S. MARTINHO DO SOUTO (CRUZ.),S. MARTINHO DO SOUTO,MOIMENTINHA (CRUZ.),SANTINHO,CEPÕES (CEMITÉRIO),CEPÕES (ESCOLA),CEPÕES,LIDL.1,HOSPITAL.1,ESCOLA RURAL.1,LECLERC,AV. DR. EGAS MONIZ (TAMBOREIRA).1,ESC. SEC. SÉ / RUA DA CALÇADA,CASA DA LAVOURA,CASA DAS BROLHAS,LARGO DE CAMÕES.1,CENTRAL DE CAMIONAGEM.1,sabado
0,08:00:00,08:01:00,08:02:00,08:03:00,08:04:00,08:05:00,08:06:00,08:07:00,08:08:00,08:09:00,08:10:00,08:11:00,08:12:00,08:13:00,08:14:00,08:15:00,08:16:00,08:17:00,08:18:00,08:20:00,08:21:00,08:22:00,08:23:00,08:24:00,08:25:00,08:26:00,08:27:00,08:28:00,08:29:00,0
1,09:00:00,09:01:00,09:02:00,09:03:00,09:04:00,09:05:00,09:06:00,09:07:00,09:08:00,09:09:00,09:10:00,09:11:00,09:12:00,09:13:00,09:14:00,09:15:00,09:16:00,09:17:00,09:18:00,09:20:00,09:21:00,09:22:00,09:23:00,09:24:00,09:25:00,09:26:00,09:27:00,09:28:00,09:29:00,0
2,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,0
3,12:00:00,12:01:00,12:02:00,12:03:00,12:04:00,12:05:00,12:06:00,12:07:00,12:08:00,12:09:00,12:10:00,12:11:00,12:12:00,12:13:00,12:14:00,12:15:00,12:16:00,12:17:00,12:18:00,12:20:00,12:21:00,12:22:00,12:23:00,12:24:00,12:25:00,12:26:00,12:27:00,12:28:00,12:29:00,0
4,13:00:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,0